import Head from 'next/head'
import Header from './header'

export default function Layout({ children }) {
  return (
    <div className="layout">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className='children-div'>
        {children}
      </div>
      <div className='footer'>

      </div>
    </div>
  )
}